Algoritmo "Antecessor"
    // Declaração de variáveis
    Var
        valor, antecessor: Inteiro

    // Início do algoritmo
    Inicio
        // Leitura do valor
        Escreva("Digite um número: ")
        Leia(valor)

        // Calcular o antecessor
        antecessor <- valor - 1

        // Exibir o antecessor
        Escreva("O antecessor de ", valor, " é ", antecessor)
Fimalgoritmo
